title: Where's Zombie?
hero_image: images/banner.png
description: Use GPS on your phone to play an outdoor zombie game. Collect the supplies but avoid the zombies!
theme: yellow # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "html/css"
steps:
  - title: Introduction
  - title: What you will need
  - title: Create the map
  - title: Retrieve the marker data
  - title: Create the markers
  - title: Display your current position
  - title: Test the GPS
  - title: Attack of the smileys
  - title: Find the items
  - title: Safety when playing the game
  - title: "Challenge: improve the game"
